# Generated by Django 5.2.6 on 2025-09-29 08:54

import book_review.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('year_of_birth', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('FTSY', 'Fantasy'), ('SCIFI', 'Science Fiction'), ('MYST_THRILL', 'Mystery/Thriller'), ('ROM', 'Romance'), ('HIST_FIC', 'Historical Fiction'), ('HORROR', 'Horror'), ('DYST', 'Dystopian'), ('ADVN', 'Adventure'), ('BIO_AUTOBIO', 'Biography/Autobiography'), ('SELF_HELP', 'Self Help'), ('HIST', 'History'), ('SCI', 'Science'), ('BSNS', 'Business')], default='FTSY', max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('cover_image', models.ImageField(default='default-cover.jpg', upload_to=book_review.models.book_cover_upload_to)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_review.author')),
            ],
        ),
    ]
