# Generated by Django 5.2.6 on 2025-09-29 09:14

import book_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='defaults/default-cover.jpg', upload_to=book_review.models.book_cover_upload_to),
        ),
    ]
