# Generated by Django 5.2.6 on 2025-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('WK', 'Work'), ('PSNL', 'Personal'), ('IDEAS', 'Ideas')], default='PSNL', max_length=5)),
            ],
        ),
    ]
