# Generated by Django 5.2.6 on 2025-09-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_added_at_alter_note_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='added_at',
        ),
    ]
