# Generated by Django 5.2.5 on 2025-09-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='defaults/default_author.jpg', upload_to='author_images/'),
        ),
    ]
